// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginScreenshot() {
  return window['go']['main']['App']['BeginScreenshot']();
}

export function CancelScreenshot() {
  return window['go']['main']['App']['CancelScreenshot']();
}

export function DeleteConfiguration(arg1) {
  return window['go']['main']['App']['DeleteConfiguration'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteProviderModel(arg1) {
  return window['go']['main']['App']['DeleteProviderModel'](arg1);
}

export function GetConfiguration(arg1) {
  return window['go']['main']['App']['GetConfiguration'](arg1);
}

export function GetConfigurations() {
  return window['go']['main']['App']['GetConfigurations']();
}

export function GetExecution(arg1) {
  return window['go']['main']['App']['GetExecution'](arg1);
}

export function GetHotkey() {
  return window['go']['main']['App']['GetHotkey']();
}

export function GetProviderModels(arg1) {
  return window['go']['main']['App']['GetProviderModels'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetStorageSettings() {
  return window['go']['main']['App']['GetStorageSettings']();
}

export function HideOverlay() {
  return window['go']['main']['App']['HideOverlay']();
}

export function InvokeConfiguration(arg1, arg2) {
  return window['go']['main']['App']['InvokeConfiguration'](arg1, arg2);
}

export function ListExecutions(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ListExecutions'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PreviewScreenshot(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PreviewScreenshot'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveConfiguration(arg1) {
  return window['go']['main']['App']['SaveConfiguration'](arg1);
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SaveProviderModel(arg1) {
  return window['go']['main']['App']['SaveProviderModel'](arg1);
}

export function SetHotkey(arg1) {
  return window['go']['main']['App']['SetHotkey'](arg1);
}

export function SetStorageSettings(arg1) {
  return window['go']['main']['App']['SetStorageSettings'](arg1);
}

export function StartConfigurationStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartConfigurationStream'](arg1, arg2, arg3);
}

export function StartScreenshotStream(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['StartScreenshotStream'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function ToggleOverlay() {
  return window['go']['main']['App']['ToggleOverlay']();
}
